package com.app.oldPos;

// Generated 2011-2-4 1:10:40 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;



/**
 * SmFunction generated by hbm2java
 */
public class SmFunctionDTO  {
	private static final long serialVersionUID = 1L;
	private String pkFunction;
	private String funcode;
	private String funname;
	private String fathercode;
	private String fatherid;
	private Integer dr;
	private Date ts;
	private String classpath;
	private Integer iexecute;
	private String pkCorp;
	private String corpcode;
	private String corpname;
	private Integer isbutton;

	private SmFunctionDTO[] buttons;

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.getFunname();
	}

	public String getPkFunction() {
		return this.pkFunction;
	}

	public void setPkFunction(String pkFunction) {
		this.pkFunction = pkFunction;
	}

	public String getFuncode() {
		return this.funcode;
	}

	public void setFuncode(String funcode) {
		this.funcode = funcode;
	}

	public String getFunname() {
		return this.funname;
	}

	public void setFunname(String funname) {
		this.funname = funname;
	}

	public String getFathercode() {
		return this.fathercode;
	}

	public void setFathercode(String fathercode) {
		this.fathercode = fathercode;
	}

	public String getFatherid() {
		return this.fatherid;
	}

	public void setFatherid(String fatherid) {
		this.fatherid = fatherid;
	}

	public Integer getDr() {
		return this.dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	public String getClasspath() {
		return this.classpath;
	}

	public void setClasspath(String classpath) {
		this.classpath = classpath;
	}

	public Integer getIexecute() {
		return this.iexecute;
	}

	public void setIexecute(Integer iexecute) {
		this.iexecute = iexecute;
	}

	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	/**
	 * @return the isbutton
	 */
	public Integer getIsbutton() {
		return isbutton;
	}

	/**
	 * @param isbutton the isbutton to set
	 */
	public void setIsbutton(Integer isbutton) {
		this.isbutton = isbutton;
	}

	/**
	 * @return the corpcode
	 */
	public String getCorpcode() {
		return corpcode;
	}

	/**
	 * @param corpcode the corpcode to set
	 */
	public void setCorpcode(String corpcode) {
		this.corpcode = corpcode;
	}

	/**
	 * @return the corpname
	 */
	public String getCorpname() {
		return corpname;
	}

	/**
	 * @param corpname the corpname to set
	 */
	public void setCorpname(String corpname) {
		this.corpname = corpname;
	}

	public SmFunctionDTO[] getButtons() {
		return buttons;
	}

	public void setButtons(SmFunctionDTO[] buttons) {
		this.buttons = buttons;
	}

	
	
}
