package com.app.oldPos;

import java.util.Date;



// Generated 2011-2-4 1:10:40 by Hibernate Tools 3.4.0.Beta1


/**
 * SmUser generated by hbm2java
 */
public class SmUserDTO  {

	private String cuserid;
	private String username;
	private String usercode;
	private String userPassword;
	private Integer dr;
	private Date ts;
	private String pkCorp;
	private String corpcode;
	private String corpname;
	
	
	public String getCuserid() {
		return this.cuserid;
	}

	public void setCuserid(String cuserid) {
		this.cuserid = cuserid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Integer getDr() {
		return this.dr;
	}

	public void setDr(Integer dr) {
		this.dr = dr;
	}

	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	public String getPkCorp() {
		return this.pkCorp;
	}

	public void setPkCorp(String pkCorp) {
		this.pkCorp = pkCorp;
	}

	/**
	 * @return the corpcode
	 */
	public String getCorpcode() {
		return corpcode;
	}

	/**
	 * @param corpcode the corpcode to set
	 */
	public void setCorpcode(String corpcode) {
		this.corpcode = corpcode;
	}

	/**
	 * @return the corpname
	 */
	public String getCorpname() {
		return corpname;
	}

	/**
	 * @param corpname the corpname to set
	 */
	public void setCorpname(String corpname) {
		this.corpname = corpname;
	}

	

}
